#!/bin/bash

target=$1;
prog_name=$0

_help() {
	echo "$0 -- Clean CHB"
	echo "usage: $prog_name"
	exit 0;
}
build_info() {
	echo "build info: $1"
}

(cd ./ && make clean)

build_info "clean finished!!!"

exit 0

