#!/bin/bash

# compile -- compile CHB
#
# Copyright (C) 2021 - 2025 andres26
#
# This file is distributed under the terms of the MIT license.
#

target=$1;
prog_name=$0;

_help() {
	echo "$0 -- Build CHB"
	echo "usage: $prog_name (first) ..."
	echo "first argument: target prefix e.j. x86_64-elf"
	exit 0;
}

build_warning() {
	echo "build warning: $1"
}

build_info() {
	echo "build info: $1"
}

if [ -z $1 ]; then
	build_warning "target is not specified, using default toolchain, for avoid this view $0 help to view help"
elif [ $1 == "help" ]; then
	_help;
fi

set -e
. ./configure $target

(cd ./ && $MAKE all)

build_info "build finished!!!"

exit 0

